### PR TITLE
243-fix-crash-when-no-location-permission

### LINKED ISSUE #243: Make iOS not require location permission if its not needed
Some apps might want to display an app without user location, in that case the permission `NSLocationWhenInUseUsageDescription` should not be required and the app should not crash on startup.

This would be consistent with android

### PR DESCRIPTION
**Pull request by JulianBissekkou**
This fixes #243.

### CODE REVIEW

File: example/ios/Podfile [hunk 1]
```diff
@@ -2,7 +2,7 @@ source 'https://cdn.cocoapods.org/'
 source 'https://github.com/m0nac0/flutter-maplibre-podspecs.git'
 
 # Uncomment this line to define a global platform for your project
-platform :ios, '9.0'
+platform :ios, '11.0'
```
Comment (m0nac0) [inline example/ios/Podfile]: Are there any specific reasons for the changes in the example/ios folder?

Comment (m0nac0) [reply example/ios/Podfile]: Or were these changes generated automatically?

File: lib/src/mapbox_map.dart [hunk 2]
```diff
@@ -28,7 +28,7 @@ class MaplibreMap extends StatefulWidget {
     this.trackCameraPosition = false,
     this.myLocationEnabled = false,
     this.myLocationTrackingMode = MyLocationTrackingMode.None,
-    this.myLocationRenderMode = MyLocationRenderMode.COMPASS,
+    this.myLocationRenderMode = MyLocationRenderMode.NORMAL,
```
Comment (m0nac0) [inline lib/src/mapbox_map.dart:31]: I think this is a good approach, but we should note this in the release notes, since it's a breaking change.

File: lib/src/mapbox_map.dart [hunk 3]
```diff
@@ -55,7 +55,13 @@ class MaplibreMap extends StatefulWidget {
     ],
     this.useDelayedDisposal,
     this.useHybridCompositionOverride,
-  })  : assert(annotationOrder.length <= 4),
+  })  : assert(
```
Comment (m0nac0) [inline lib/src/mapbox_map.dart:58]: Good idea!

File: lib/src/mapbox_map.dart (hunk 2 above)
Comment (m0nac0) [reply lib/src/mapbox_map.dart:31]: PR for changelog docs: #247

File: example/ios/Podfile (hunk 1 above)
Comment (JulianBissekkou) [reply example/ios/Podfile]: Yes, I executed the example app with flutter 3.10.1 and it generates those and a few other changes.

File: lib/src/mapbox_map.dart (hunk 2 above)
Comment (JulianBissekkou) [reply lib/src/mapbox_map.dart:31]: Thanks for writing the changelog for me :)

Comment (JulianBissekkou) [reply lib/src/mapbox_map.dart:31]: Should I adjust the documentation to highlight that you only need location permission if you use specific properties?

**Comment by JulianBissekkou** [comment]
@m0nac0 
Let me know if there are any open changes that you would like me to do 👍🏽

**Comment by stefanschaller** [comment]
@mariusvn  Could you may check that out? @m0nac0  is not responding and we need the fixes.

**Comment by mariusvn** [comment]
I can check it out but i dont have any rights so can't do a lot. m0nac0 is sometimes inactive but he will come back, i recommend to create a fork with the modification you need for temporary purposes

**Comment by JulianBissekkou** [comment]
@m0nac0  Can you check so we can merge this sometime?

**Review by stefanschaller — APPROVED** [review]

**Comment by m0nac0** [comment]
Sorry you had to wait with this PR... LGTM, could you update the base branch? Then it should be merged automatically.
