### PR TITLE
fix(web): ensure the usage of `maplibre-gl-js` version 4.x.x, remove `_addStylesheetToShadowRoot`

### LINKED ISSUE #331: Investigate how to include the correct css stylesheet on the web
Currently, in https://github.com/maplibre/flutter-maplibre-gl/blob/6d24384ed93172f2680a20bf451df795aac21daa/maplibre_gl_web/lib/src/maplibre_web_gl_platform.dart#L179-L185 
we automatically load a maplibre CSS stylesheet (from https://github.com/maplibre/flutter-maplibre-gl/blob/6d24384ed93172f2680a20bf451df795aac21daa/maplibre_gl_web/lib/src/maplibre_web_gl_platform.dart#L4-L5)

But in the Readme, we also tell developers to add a maplibre css stylesheet to their index.html in https://github.com/maplibre/flutter-maplibre-gl/blob/6d24384ed93172f2680a20bf451df795aac21daa/README.md?plain=1#L59-L65

In my tests, only the stylesheet we automatically add seems to matter, removing the other one seems to have no effect.
We should investigate this, and possibly update the version and change the instructions for developers in the Readme.

### PR DESCRIPTION
**Pull request by josxha**
- At the moment the package uses the latest maplibre-gl-js version in the example app. This could introduce unwanted breaking changes to the example app. This pull request limits the version to the latest version 4 release (4.x.x).
- The web package is using still v1.13.0-rc.4 of `mapbox-gl.css` from cdn.maptiler.com internally. This code has been added in an early stage of flutter web (maybe as a workaround in the early stage of flutter web?). The example app works the same without it, so I guess it's no longer needed and therefore removed in this pull request.
  - Update: This code was added because of https://github.com/flutter-mapbox-gl/maps/issues/514
- The web project files have significantly changed a lot since they were generated. This pull request recreates the web files of the example project.

### CODE REVIEW

File: maplibre_gl_web/lib/src/maplibre_web_gl_platform.dart [hunk 1]
```diff
@@ -1,9 +1,5 @@
 part of maplibre_gl_web;
 
-//TODO Url taken from the Maptiler tutorial; use official and stable release once available
-final _maplibreGlCssUrl =
-    'https://cdn.maptiler.com/maplibre-gl-js/v1.13.0-rc.4/mapbox-gl.css';
```
Comment (kuhnroyal) [inline maplibre_gl_web/lib/src/maplibre_web_gl_platform.dart:5]: So this is now available via the 4.3 dist stylesheet?

File: example/web/index.html [hunk 2]
```diff
@@ -9,29 +24,19 @@
...
-       https://developers.google.com/web/fundamentals/primers/service-workers -->
-  <script>
-    if ('serviceWorker' in navigator) {
-      window.addEventListener('load', function () {
-        navigator.serviceWorker.register('/flutter_service_worker.js');
-      });
-    }
-  </script>
-  <script src="main.dart.js" type="application/javascript"></script>
+  <script src="flutter_bootstrap.js" async></script>
```
Comment (kuhnroyal) [inline example/web/index.html]: Do you know in which Flutter version this bootstrap script was added.

Comment (josxha) [reply example/web/index.html]: It got added in 3.22.

File: maplibre_gl_web/lib/src/maplibre_web_gl_platform.dart (hunk 1 above)
Comment (josxha) [reply maplibre_gl_web/lib/src/maplibre_web_gl_platform.dart:5]: My guess was that injecting it here was a workaround in the times of early stage dart js interop. I tried to figure out some information about the problem back then but wasn't successful. The example app works the same without it and I couldn't find a reason leaving it in.

File: example/web/index.html (hunk 2 above)
Comment (kuhnroyal) [reply example/web/index.html]: Ok but then we need to bump the Flutter version in the pubspec?

Comment (josxha) [reply example/web/index.html]: Could be, sorry I don't know if there is any backwards compatibility. But because this does only affects the example app the version bump shouldn't be that much of a program, right? However, because we are using an outdated version in the CI, it will probably fail if we increase the min version.

Comment (kuhnroyal) [reply example/web/index.html]: I think we should stick with the old bootstrapping for now, so that it actually works without designated min SDK.

File: maplibre_gl_web/pubspec.yaml [hunk 3]
```diff
@@ -34,4 +34,4 @@ dev_dependencies:
 
 environment:
   sdk: ">=2.12.0 <3.0.0"
-  flutter: ">=2.0.0"
+  flutter: ">=2.0.0"
```
Comment (kuhnroyal) [inline maplibre_gl_web/pubspec.yaml]: newline got removed here

**Comment by josxha** [comment]
I reverted the recreation of the example web project.

**Review by kuhnroyal — APPROVED** [review]
