### PR TITLE
Fix offline region download crashing the example app

### LINKED ISSUE #183: Demo App crashes on downloading offline regions
In the demo app, when i download an offline region i get a SIGSEGV

```
E/libc++abi(24378): terminating with uncaught exception of type std::__ndk1::regex_error: The expression contained an invalid range in a {} expression.
F/libc    (24378): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 24587 (DatabaseFileSou), pid 24378 (mapboxglexample)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HUAWEI/CMR-W09/HWCMR09:9/HUAWEICMR-W09/9.1.0.335C432:user/release-keys'
Revision: '0'
ABI: 'arm64'
Happend: 'Thu Dec 22 11:10:35 2022
'
SYSVMTYPE: Art
APPVMTYPE: Art
pid: 24378, tid: 24587, name: DatabaseFileSou  >>> com.mapbox.mapboxglexample <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'terminating with uncaught exception of type std::__ndk1::regex_error: The expression contained an invalid range in a {} expression.'
    x0  0000000000000000  x1  000000000000600b  x2  0000000000000006  x3  0000000000000008
    x4  fefeff79ff2d6d6e  x5  fefeff79ff2d6d6e  x6  fefeff79ff2d6d6e  x7  7f7f7f7f7f7f7f7f
    x8  0000000000000083  x9  d56d183b142ee75a  x10 0000000000000000  x11 fffffffc7ffffbdf
    x12 0000000000000001  x13 0000000063a42d1a  x14 000e34d3673516e7  x15 00000716c75550b0
    x16 0000007db68b32c0  x17 0000007db67f233c  x18 0000000000000001  x19 0000000000005f3a
    x20 000000000000600b  x21 0000007bf377e338  x22 ffffff80ffffffc8  x23 0000007bf377e3f0
    x24 0000007bf377e2d0  x25 0000007bf377e310  x26 0000007bf377ebb8  x27 0000000000000018
    x28 0000007bf377eba0  x29 0000007bf377e240
    sp  0000007bf377e200  lr  0000007db67e6e68  pc  0000007db67e6e90
backtrace:
    #00 pc 0000000000022e90  /system/lib64/libc.so (abort+116)
    #01 pc 00000000002fc2a4  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #02 pc 00000000002fc3fc  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #03 pc 00000000002f99d4  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #04 pc 00000000002f9000  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #05 pc 00000000002f8f5c  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so (__cxa_throw+112)
    #06 pc 000000000019886c  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #07 pc 000000000019869c  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #08 pc 000000000019b0a8  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #09 pc 0000000000197d54  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #10 pc 0000000000197a1c  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #11 pc 0000000000197134  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #12 pc 000000000021fc94  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #13 pc 000000000021f760  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #14 pc 00000000001b289c  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #15 pc 00000000000ea37c  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #16 pc 00000000001af24c  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #17 pc 00000000001af360  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #18 pc 00000000001aed94  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #19 pc 00000000002178f0  /data/app/com.mapbox.mapboxglexample-pl4b2eQuS_tcz18flpT5kg==/lib/arm64/libmapbox-gl.so
    #20 pc 0000000000083a6c  /system/lib64/libc.so (__pthread_start(void*)+36)
    #21 pc 00000000000246e4  /system/lib64/libc.so (__start_thread+68)
```

### PR DESCRIPTION
**Pull request by kuhnroyal**
The offline region downloads don't seem to work with the demo style due to them being hosted on Github pages. There is always a hard crash somewhere in native code (maplibre-native) on both iOS and Android.

Fixes https://github.com/maplibre/flutter-maplibre-gl/issues/183

### CODE REVIEW

File: maplibre_gl/lib/src/maplibre_styles.dart [hunk 1]
```diff
@@ -7,5 +7,9 @@ typedef MaplibreStyles = MapLibreStyles;
 abstract class MapLibreStyles {
   /// A very simple MapLibre demo style that shows only countries with their
   /// boundaries.
-  static const String demo = "https://demotiles.maplibre.org/style.json";
+  static const String demo = 'https://demotiles.maplibre.org/style.json';
+
+  /// The OpenFreeMap liberty style
+  static const String openfreemapLiberty =
```
Comment (felix-ht) [inline maplibre_gl/lib/src/maplibre_styles.dart:13]: maybe move this to another class and file?

OpenFreeMapStyles
