### PR TITLE
Fix: Update of generate.dart and its template files. Fixed Offset, Translate and expressions arrays on iOS.

### LINKED ISSUE #148: LineLayerProperties lineDasharray not working
Hi all,
I'm trying to add two lines with a line-dasharray property as a new source.
```
_mapController.addSource(
      "off-piste-section",
      GeojsonSourceProperties(
        data:
          {  "type": "FeatureCollection",
          "crs": { "type": "name", "properties": { "name": "off-piste-section" } },
          "features": [
          { "type": "Feature", "properties": { "id": "off-piste-section-line1"},  
            "geometry": { "type": "LineString", 
            "coordinates": [ [-151.2484, 61.2705, 0 ], [0, 0, 0 ]] } },
          { "type": "Feature", "properties": { "id": "off-piste-section-line2" }, 
            "geometry": { "type": "LineString", 
            "coordinates": [ [180.2484, 60.2705, 0 ], [0, 0, 0 ]], } },        
          ]
        },
      )
    ).then((value) {
      _mapController.addLayer(
        "off-piste-section",
        "off-piste-section-line",
        LineLayerProperties(
          lineWidth: 6,
          lineColor: "#de0202",
          lineOpacity: 0.9,
          lineCap: "round",
          lineJoin: "round",  
          lineDasharray: [5, 2]
        ));
    });
```
Adding the source works fine and also all other attributes are working. Except the lineDasharry attribute.
The following error is given by the console:
`Error setting property: line-dasharray value must be an array of numbers`

Adding the same layer in the style.json, works fine.
```
    {
      "id": "off-piste-section-line",
      "type": "line",
      "source": "off-piste-section",
      "paint": {
        "line-dasharray": [5, 2],
        "line-width": 6,
        "line-opacity": 0.9,
        "line-color": "rgba(222, 2, 2, 1)"
      }
    }
```

Looks like an error in the flutter binding. Maybe just a small issue.

### LINKED ISSUE #480: [BUG] Offsets, translations, and other properties that accept arrays get crash on iOS.
### Platforms
- iOS
- Android

### Version of flutter maplibre_gl

main branch

### Bug Description

The property line-dasharray for Line layers doesn't correctly work on iOS Platform.
When attempting to assign the property with an expression as a value, upon Line creation, the app crashes.

Actually, this issue is only on iOS, on Android correctly works. I don't know for web platform.

### Steps to Reproduce

1. Create a Line Layer using controller.addLineLayer.
2. Use the property "lineDasharray" in the LineLayerProperties.
   - Assign this expression to the property:
     ```dart
     lineDasharray: [
         "literal",
         [4, 2],
     ]
     ```
3. When the map attempts to add the Line, the app crashes.
   - On Android the app doesn't crash but an error log appears:
     > {aplibre.example}[JNI]: Property setting error: icon-offset value must be an array of 2 numbers.

### Expected Results

1. Create a Line Layer using controller.addLineLayer.
2. Use the property "lineDasharray" in the LineLayerProperties.
   - Assign this expression to the property:
     ```dart
     lineDasharray: [
         "literal",
         [4, 2],
     ]
     ```
3. The controller correctly adds the Line and renders it.

### Actual Results

image

### Code Sample

```dart
await controller?.addLineLayer(
  "$collectionName-source",
  layerId,
  LineLayerProperties(
     lineColor: getRandomColor,
     lineWidth: 2.0,
     lineDasharray: [
        "literal",
        [4, 2],
     ],
  ),
  enableInteraction: true, 
);
```

### PR DESCRIPTION
**Pull request by gabbopalma**
Hi guys, this PR aims to solve the [#480 issue](https://github.com/maplibre/flutter-maplibre-gl/issues/480) that I opened recently.

I started by refactoring all template files, used in generate.dart, updating them because they were obsolete (there were still some mapbox references inside).
Next, I fixed some problems with the paths in generate.dart, which were also obsolete.

Testing #480, I realized that the problem wasn't only with the “line-dasharray” property, but with all arrays that were part of a linear expression or that were arrays of doubles (generally numbers).
I introduced some checks in LayerPropertyConverter.swift and now every array or expression, for every property (even on Offset and Translate, which work with the CGVector class), works correctly on the iOS platform.

### CODE REVIEW

**Comment by kuhnroyal** [comment]
Thanks for all the namespace/path fixes, I completely missed those in the generator.
Do we need adjustments for #480 on the Android side as well or is everything working there?

**Comment by gabbopalma** [comment]
> Thanks for all the namespace/path fixes, I completely missed those in the generator.
> 
> Do we need adjustments for #480 on the Android side as well or is everything working there?

@kuhnroyal On Android everything was fine for line-patharray, but it only accepts expressions and not arrays, when using an array a console error appears with "array not allowed".
Other than that, I haven't checked the properties of offsets or translations, but I think everything is fine on Android, I might check on Monday.

Do we want to accept only expressions on iOS as well? Currently, with my edits, arrays are also allowed on iOS (I think this must be the correct way also on Android, for a better UX).

**Comment by gabbopalma** [comment]
@kuhnroyal I did some checking on Android, and well, the bug isn't only on iOS but also on Android. But on Android it doesn't cause a crash, just an error log:
>{aplibre.example}[JNI]: Property setting error: icon-offset value must be an array of 2 numbers.

These days I will fix the LayerPropertConverter.java, also applying some optimization fixes, in case I will update you with commits and comments here.

**Comment by gabbopalma** [comment]
Hi guys, any update on this?

File: maplibre_gl/android/src/main/java/org/maplibre/maplibregl/LayerPropertyConverter.java [hunk 1]
```diff
@@ -65,7 +74,16 @@ static PropertyValue[] interpretSymbolLayerProperties(Object o) {
           properties.add(PropertyFactory.textHaloBlur(expression));
           break;
         case "text-translate":
-          properties.add(PropertyFactory.textTranslate(expression));
+          if (jsonElement.isJsonArray()) {
```
Comment (Zverik) [inline maplibre_gl/android/src/main/java/org/maplibre/maplibregl/LayerPropertyConverter.java:77]: Maybe put all this logic into `convertJsonToFloatArray` to avoid repetition?..

**Review by Zverik — COMMENTED** [review]
Generally seems ok to me, and solves a bug in theory.

File: maplibre_gl/android/src/main/java/org/maplibre/maplibregl/LayerPropertyConverter.java (hunk 1 above)
Comment (gabbopalma) [reply maplibre_gl/android/src/main/java/org/maplibre/maplibregl/LayerPropertyConverter.java:77]: I actually don't remember why I did this, it was a while ago. Maybe because in some cases the conversion was handled differently, but currently it seems logical to put everything in `convertJsonToFloatArray`.

**Review by josxha — APPROVED** [review]
